FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app
RUN make server
EXPOSE 9000
VOLUME ["/app/server_files"]
CMD ["/app/server", "9000", "/app/server_files"]
